# Generated by Django 4.2.7 on 2023-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descr',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
